// Fotografije sa 13. Savetovanja HRANA, ISHRANA & ZDRAVLJE (06.10.2026, Hotel Crowne Plaza, Beograd).
// Fajlovi su u public/assets/img/gallery/13-savetovanje; opis (alt) je na srpskom i engleskom.
export const FOTO_13_SAVETOVANJE = [
  { file: "13-savetovanje-izlaganje-za-govornicom-01.jpg", sr: "Izlaganje za govornicom i sto predavača na 13. savetovanju HRANA, ISHRANA & ZDRAVLJE", en: "Speaker at the lectern and the speakers’ table at the 13th FOOD, NUTRITION & HEALTH conference" },
  { file: "13-savetovanje-puna-sala-crowne-plaza-02.jpg", sr: "Puna sala hotela Crowne Plaza u Beogradu na 13. savetovanju", en: "A full conference hall at Hotel Crowne Plaza, Belgrade" },
  { file: "13-savetovanje-ucesnici-u-sali-03.jpg", sr: "Učesnici savetovanja u sali hotela Crowne Plaza", en: "Conference participants in the Hotel Crowne Plaza hall" },
  { file: "13-savetovanje-sala-tokom-predavanja-04.jpg", sr: "Sala tokom predavanja, pogled sa bine", en: "The hall during a lecture, seen from the stage" },
  { file: "13-savetovanje-sala-i-sto-predavaca-05.jpg", sr: "Sala savetovanja sa stolom predavača", en: "The conference hall with the speakers’ table" },
  { file: "13-savetovanje-predavanje-pred-punom-salom-06.jpg", sr: "Predavanje za govornicom pred punom salom", en: "A lecture at the lectern in front of a full hall" },
  { file: "13-savetovanje-predavacica-za-govornicom-07.jpg", sr: "Predavačica za govornicom na 13. savetovanju", en: "A speaker at the lectern at the 13th conference" },
  { file: "13-savetovanje-predavanje-za-govornicom-08.jpg", sr: "Predavanje za govornicom, pogled na salu", en: "A lecture at the lectern, with a view of the hall" },
  { file: "13-savetovanje-obracanje-ucesnicima-09.jpg", sr: "Predavačica se obraća učesnicima savetovanja", en: "A speaker addressing the conference participants" },
  { file: "13-savetovanje-ucesnici-prate-prezentaciju-10.jpg", sr: "Učesnici prate prezentaciju na savetovanju", en: "Participants following a presentation" },
  { file: "13-savetovanje-ucesnici-za-stolovima-11.jpg", sr: "Učesnici 13. savetovanja za stolovima u sali", en: "Participants of the 13th conference at their tables" },
  { file: "13-savetovanje-prezentacija-na-platnu-12.jpg", sr: "Učesnici prate prezentaciju na platnu", en: "Participants watching a presentation on screen" },
  { file: "13-savetovanje-publika-tokom-predavanja-13.jpg", sr: "Publika tokom predavanja na savetovanju", en: "The audience during a lecture" },
  { file: "13-savetovanje-pogled-iz-publike-14.jpg", sr: "Pogled iz publike na predavanje i prezentaciju", en: "View from the audience toward the lecture and slides" },
  { file: "13-savetovanje-ucesnici-prate-predavanje-15.jpg", sr: "Učesnici savetovanja prate predavanje", en: "Conference participants following a lecture" },
  { file: "13-savetovanje-redovi-ucesnika-16.jpg", sr: "Redovi učesnika u sali savetovanja", en: "Rows of participants in the conference hall" },
  { file: "13-savetovanje-kraj-predavanja-17.jpg", sr: "Kraj predavanja – „Hvala na pažnji“ na platnu", en: "End of a lecture – “Thank you for your attention” on screen" },
  { file: "13-savetovanje-strucno-predavanje-18.jpg", sr: "Učesnici tokom stručnog predavanja", en: "Participants during an expert lecture" },
  { file: "13-savetovanje-okrugli-sto-pitanja-iz-industrije-19.jpg", sr: "Okrugli sto: stručnjaci odgovaraju na pitanja iz industrije", en: "Round table: experts answer questions from the industry" },
  { file: "13-savetovanje-okrugli-sto-moderatorka-20.jpg", sr: "Moderatorka za govornicom i panelisti okruglog stola", en: "The moderator at the lectern and the round-table panelists" },
  { file: "13-savetovanje-panelisti-i-sala-21.jpg", sr: "Panelisti okruglog stola i učesnici u sali", en: "Round-table panelists and participants in the hall" },
  { file: "13-savetovanje-diskusija-okrugli-sto-22.jpg", sr: "Diskusija tokom okruglog stola", en: "Discussion during the round table" },
  { file: "13-savetovanje-stand-mc-labor-23.jpg", sr: "Štand kompanije MC Labor na 13. savetovanju", en: "The MC Labor stand at the 13th conference" },
  { file: "13-savetovanje-ucesnici-na-standu-mc-labor-24.jpg", sr: "Učesnici na štandu kompanije MC Labor tokom pauze", en: "Participants at the MC Labor stand during the break" },
  { file: "13-savetovanje-stand-biokom-25.jpg", sr: "Štand kompanije Biokom na 13. savetovanju", en: "The Biokom stand at the 13th conference" },
  { file: "13-savetovanje-razgovor-na-standu-biokom-26.jpg", sr: "Razgovor sa predstavnicima kompanije Biokom", en: "Talking with Biokom representatives" },
  { file: "13-savetovanje-pauza-za-kafu-lobi-27.jpg", sr: "Pauza za kafu u lobiju hotela Crowne Plaza", en: "Coffee break in the Hotel Crowne Plaza lobby" },
  { file: "13-savetovanje-kafe-pauza-i-standovi-28.jpg", sr: "Kafe pauza i štandovi sponzora", en: "Coffee break and sponsor stands" },
  { file: "13-savetovanje-druzenje-tokom-pauze-29.jpg", sr: "Druženje učesnika tokom pauze", en: "Participants networking during the break" },
  { file: "13-savetovanje-razgovori-pored-standova-30.jpg", sr: "Razgovori učesnika pored štandova sponzora", en: "Participants talking by the sponsor stands" },
  { file: "13-savetovanje-pauza-izmedju-predavanja-31.jpg", sr: "Učesnici u pauzi između predavanja", en: "Participants in the break between lectures" },
  { file: "13-savetovanje-susret-strucnjaka-32.jpg", sr: "Susret stručnjaka iz industrije tokom pauze", en: "Industry professionals meeting during the break" },
  { file: "13-savetovanje-razmena-iskustava-33.jpg", sr: "Razmena iskustava među učesnicima savetovanja", en: "Participants exchanging experiences" },
  { file: "13-savetovanje-zajednicka-fotografija-34.jpg", sr: "Zajednička fotografija učesnica savetovanja", en: "Group photo of conference participants" },
];
